# Generated by Django 6.0.6 on 2026-07-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='SatClassCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sat_class_category_map',
            },
        ),
        migrations.CreateModel(
            name='VendorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'vendor_rules',
            },
        ),
        migrations.CreateModel(
            name='VendorCategoryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_rfc', models.CharField(max_length=13)),
                ('sender_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0)),
                ('times_confirmed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_caches', to='classification.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_category_cache',
                'unique_together': {('tenant', 'sender_rfc')},
            },
        ),
    ]
