import React from 'react';
import { View, Text, ScrollView, Pressable } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';

export default function SettingsStorage() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<any>();

  return (
    <View className="flex-1 bg-bg" style={{ paddingTop: insets.top }}>
      <View className="flex-row items-center px-4 py-2">
        <Pressable hitSlop={8} onPress={() => navigation.goBack()}>
          <Ionicons name="chevron-back-outline" size={24} color="#5f6368" />
        </Pressable>
        <Text className="ml-3 text-lg font-semibold text-ink">Ticket Storage</Text>
      </View>

      <ScrollView contentContainerClassName="gap-4 p-4">
        <View className="items-center rounded-lg border border-border bg-card p-8">
          <Ionicons name="archive-outline" size={40} color="#9aa0a6" />
          <Text className="mt-4 text-center text-base font-medium text-ink">
            Ticket Storage
          </Text>
          <Text className="mt-2 text-center text-sm text-muted">
            Invoices generated by Sage AI will appear here. Paste a ticket into
            Sage chat to emit a CFDI — the record lands in this list.
          </Text>
          <Text className="mt-4 text-xs font-semibold uppercase tracking-wider text-muted">
            Coming soon
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}
