# Generated by Django 6.0.6 on 2026-07-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('tenants', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('cer_path', models.CharField(max_length=255)),
                ('key_path', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sat_credentials',
                'unique_together': {('tenant', 'rfc')},
            },
        ),
        migrations.CreateModel(
            name='SatDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('download_type', models.CharField(choices=[('issued', 'Issued'), ('received', 'Received')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('querying', 'Querying'), ('verifying', 'Verifying'), ('downloading', 'Downloading'), ('finished', 'Finished'), ('error', 'Error')], default='pending', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('packages_count', models.PositiveIntegerField(default=0)),
                ('cfdis_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sat_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='sat.satcredential')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sat_download_requests',
            },
        ),
        migrations.CreateModel(
            name='SatCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('document_type', models.CharField(choices=[('issued', 'Issued'), ('received', 'Received')], max_length=20)),
                ('sender_rfc', models.CharField(max_length=13)),
                ('sender_name', models.CharField(max_length=255)),
                ('receiver_rfc', models.CharField(max_length=13)),
                ('receiver_name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=2, null=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=3, null=True)),
                ('cfdi_usage', models.CharField(blank=True, max_length=3, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('document_subtype', models.CharField(blank=True, max_length=1, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_withholding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isr_withholding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('concepts', models.JSONField(blank=True, null=True)),
                ('xml_content', models.TextField(blank=True, null=True)),
                ('category_confirmed', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('none', 'Unreviewed'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='classification.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='vendors.vendor')),
                ('sat_download_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='sat.satdownloadrequest')),
            ],
            options={
                'db_table': 'sat_cfdis',
                'indexes': [models.Index(fields=['tenant', 'document_type'], name='sat_cfdis_tenant__8a2fb3_idx'), models.Index(fields=['tenant', 'sender_rfc'], name='sat_cfdis_tenant__300da3_idx'), models.Index(fields=['tenant', 'issue_date'], name='sat_cfdis_tenant__b13864_idx'), models.Index(fields=['tenant', 'document_type', 'paid_at'], name='sat_cfdis_tenant__145991_idx'), models.Index(fields=['tenant', 'review_status'], name='sat_cfdis_tenant__0fdce5_idx')],
            },
        ),
    ]
