# Generated by Django 6.0.6 on 2026-07-05 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('business_type', models.CharField(choices=[('services', 'Services'), ('commerce', 'Commerce'), ('manufacturing', 'Manufacturing'), ('mixed', 'Mixed')], default='services', max_length=20)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('tax_regime', models.CharField(blank=True, choices=[('resico_pf', 'RESICO Individual'), ('pfae', 'Individual Business Activity'), ('professional_fees', 'Professional Fees'), ('resico_pm', 'RESICO Corporate')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tenant',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
