# Generated by Django 6.0.6 on 2026-07-05 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('sat', '0001_initial'),
        ('tenants', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_images',
            },
        ),
        migrations.CreateModel(
            name='TicketExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('ticket_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('bucket', models.CharField(choices=[('company_deductible', 'Company Deductible'), ('company_non_deductible', 'Company Non Deductible'), ('personal', 'Personal')], default='company_non_deductible', max_length=30)),
                ('has_invoice', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('none', 'Unreviewed'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_expenses', to='classification.expensecategory')),
                ('linked_cfdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tickets', to='sat.satcfdi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_expenses', to='vendors.vendor')),
                ('ticket_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_expenses', to='tickets.ticketimage')),
            ],
            options={
                'db_table': 'ticket_expenses',
            },
        ),
        migrations.AddIndex(
            model_name='ticketimage',
            index=models.Index(fields=['tenant', 'created_at'], name='ticket_imag_tenant__301f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['tenant', 'bucket'], name='ticket_expe_tenant__359839_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['tenant', 'review_status'], name='ticket_expe_tenant__6bbc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['tenant', 'ticket_date'], name='ticket_expe_tenant__73f190_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['tenant', 'has_invoice'], name='ticket_expe_tenant__d8978e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['tenant', 'vendor'], name='ticket_expe_tenant__b90b7e_idx'),
        ),
    ]
