# Generated by Django 6.0.6 on 2026-07-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('last_invoice_at', models.DateTimeField(blank=True, null=True)),
                ('is_cost_of_sales', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='classification.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['tenant', 'is_cost_of_sales'], name='vendors_tenant__c94eee_idx')],
                'unique_together': {('tenant', 'rfc')},
            },
        ),
    ]
